### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Cam-McDonnell** [cs361-W16/Group2-2#16]
view:
-Button to specify spanish or american cards (or initial choice before loading the game?)
-change card pictures based on input of above
model: (game class)
-add a spanish deckbuild to make cards values 1-7 and face cards 
-make Aces low (value 1) and change game rules based on this fact
model: (card class)
-spanish card option to change suit to cups, coins, swords and clubs (Not really necessary from what I can tell)

**Comment by kirkpatt** [comment]
Turned all these into issues.
